apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/provider-upjet-mysql
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: A Crossplane provider for MySQL
  name: provider-upjet-mysql
